storageaccountname = "shubhamjdshdsd8"
resource_group_name="st-gr"
location="UAE North"
account_tier = "Standard"
account_replication_type = "GRS"
stcontainer = "stcont"
container_access_type = "private"
azurerm_key_vault = "keyvault78fv"